package com.iii.twentywork.model.bean;
// Generated 2016/1/10 �U�� 06:05:34 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Board generated by hbm2java
 */
public class Board implements java.io.Serializable
{
    private static final long serialVersionUID = 1L;

	@Override
	public String toString() {
		return "Board [boardId=" + boardId + ", boardTitle=" + boardTitle + ", boardText=" + boardText + ", boardTime="
				+ boardTime + "]";
	}

	private String boardId;
	private BoardClass boardClass;
    private TeamBean team;
    private UsersBean users;
    private String boardTitle;
    private String boardText;
    private Date boardTime;
    
    private Integer subNumber;

    //被user列入my Fav 的名單 
    private Set<UsersBean> userses = new HashSet<UsersBean>(0);

    //子項目
    private Set<Sub> subs = new HashSet<Sub>(0);

    public Board()
    {
    }

    public Board(String boardId, String boardTitle, Date boardTime)
    {
        this.boardId = boardId;
        this.boardTitle = boardTitle;
        this.boardTime = boardTime;
    }

    public Board(String boardId, BoardClass boardClass, TeamBean team, UsersBean users,
            String boardTitle, String boardText, Date boardTime,
            Set<UsersBean> userses, Set<Sub> subs)
    {
        this.boardId = boardId;
        this.boardClass = boardClass;
        this.team = team;
        this.users = users;
        this.boardTitle = boardTitle;
        this.boardText = boardText;
        this.boardTime = boardTime;
        this.userses = userses;
        this.subs = subs;
    }

    public String getBoardId()
    {
        return this.boardId;
    }

    public void setBoardId(String boardId)
    {
        this.boardId = boardId;
    }

    public BoardClass getBoardClass()
    {
        return this.boardClass;
    }

    public void setBoardClass(BoardClass boardClass)
    {
        this.boardClass = boardClass;
    }

    public TeamBean getTeam()
    {
        return this.team;
    }

    public void setTeam(TeamBean team)
    {
        this.team = team;
    }

    public UsersBean getUsers()
    {
        return this.users;
    }

    public void setUsers(UsersBean users)
    {
        this.users = users;
    }

    public String getBoardTitle()
    {
        return this.boardTitle;
    }

    public void setBoardTitle(String boardTitle)
    {
        this.boardTitle = boardTitle;
    }

    public String getBoardText()
    {
        return this.boardText;
    }

    public void setBoardText(String boardText)
    {
        this.boardText = boardText;
    }

    public Date getBoardTime()
    {
        return this.boardTime;
    }

    public void setBoardTime(Date boardTime)
    {
        this.boardTime = boardTime;
    }

    public Set<UsersBean> getUserses()
    {
        return this.userses;
    }

    public void setUserses(Set<UsersBean> userses)
    {
        this.userses = userses;
    }

    public Set<Sub> getSubs()
    {
        return this.subs;
    }

    public void setSubs(Set<Sub> subs)
    {
        this.subs = subs;
    }

    public Integer getSubNumber()
    {
        return subNumber;
    }

    public void setSubNumber(Integer subNumber)
    {
        this.subNumber = subNumber;
    }
    
    

}
