package com.iii.twentywork.model.bean;
// Generated 2016/1/22 �W�� 01:44:34 by Hibernate Tools 4.3.1.Final

/**
 * MyFavId generated by hbm2java
 */
public class MyFavId implements java.io.Serializable
{

    private String userId;
    private String boardId;

    public MyFavId()
    {
    }

    public MyFavId(String userId, String boardId)
    {
        this.userId = userId;
        this.boardId = boardId;
    }

    public String getUserId()
    {
        return this.userId;
    }

    public void setUserId(String userId)
    {
        this.userId = userId;
    }

    public String getBoardId()
    {
        return this.boardId;
    }

    public void setBoardId(String boardId)
    {
        this.boardId = boardId;
    }

    public boolean equals(Object other)
    {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof MyFavId))
            return false;
        MyFavId castOther = (MyFavId) other;

        return ((this.getUserId() == castOther.getUserId())
                || (this.getUserId() != null && castOther.getUserId() != null
                        && this.getUserId().equals(castOther.getUserId())))
                && ((this.getBoardId() == castOther.getBoardId())
                        || (this.getBoardId() != null
                                && castOther.getBoardId() != null
                                && this.getBoardId()
                                        .equals(castOther.getBoardId())));
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result
                + (getUserId() == null ? 0 : this.getUserId().hashCode());
        result = 37 * result
                + (getBoardId() == null ? 0 : this.getBoardId().hashCode());
        return result;
    }

}
