package com.iii.twentywork.model.bean;
// Generated 2016/1/22 �W�� 01:44:34 by Hibernate Tools 4.3.1.Final

/**
 * MyFavId generated by hbm2java
 */
public class NotifyId implements java.io.Serializable
{

    private String userId;
    private int fileId;

    
	@Override
	public String toString() {
		return "NotifyId [userId=" + userId + ", fileId=" + fileId + "]";
	}


	public NotifyId() { }


	public String getUserId() {
		return userId;
	}


	public void setUserId(String userId) {
		this.userId = userId;
	}


	public int getFileId() {
		return fileId;
	}


	public void setFileId(int fileId) {
		this.fileId = fileId;
	}


}
